### ISSUE TITLE
data has to be consumed on post requests

### ISSUE THREAD

**Issue by vpassama** [CanalTP/Chaos#183]
Thanks to the functional tests I'm currently writing ;), I wanted to check an error response from a POST method on the new endpoint /properties (see https://github.com/CanalTP/Chaos/pull/175).

The scenario I'm trying to check is a POST on /properties without any header (so no X-Contributor which is mandatory to request this endpoint, **remember this because it is important**).

Since I expected an error similar to GET /properties, I did not receive anything from the server, and the request ended on a "Could not get any response" (message in postman extension).

I didn't give up on this and I tried to use curl on the server, looking for the error message from the post request : 

```
curl http://127.0.0.1:5000/properties -d toto > test.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  3   107    0     0    0     4      0      0 --:--:--  0:00:21 --:--:--     0
```

no response after waiting for a while.

With a GET request : 

```
curl http://127.0.0.1:5000/properties > test.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   103  100   103    0     0  53785      0 --:--:-- --:--:-- --:--:--  100k

```

That's ok.

So I tried to check the log because I'm currently going in the `@validate_client()` method and I wanted to know what's happening (see the code there: [property](https://github.com/Tisseo/Chaos/blob/pull_request_vpassama_property/chaos/resources.py#L821-L831) and [validate_client](https://github.com/CanalTP/Chaos/blob/master/chaos/validate_params.py#L39-L59)).

So we use uwsgi and nginx and in uwsgi I see this : 

* **GET** `[pid: 16123|app: 0|req: 2/2] 127.0.0.1 () {32 vars in 362 bytes} [Thu Apr 21 18:08:24 2016] GET /properties => generated 103 bytes in 1 msecs (HTTP/1.1 400) 2 headers in 81 bytes (1 switches on core 4)`
* **POST** `[pid: 16123|app: 0|req: 1/1] 127.0.0.1 () {36 vars in 475 bytes} [Thu Apr 21 18:08:12 2016] POST /properties => generated 103 bytes in 1 msecs (HTTP/1.1 400) 2 headers in 81 bytes (1 switches on core 0)`

Nothing special, the two requests seem to be OK to me, so what the hell ? Let's have a look on nginx log : 

* **GET** 127.0.0.1 - - [21/Apr/2016:18:08:24 +0200] "GET /properties HTTP/1.1" 400 103 "-" "curl/7.26.0"
* **POST** 127.0.0.1 - - [21/Apr/2016:18:08:12 +0200] "POST /properties HTTP/1.1" 400 0 "-" "curl/7.26.0"

And there is the weird behavior, 103 bytes for the GET, 0 bytes for the POST, it looks like uwsgi didn't tell anything to nginx or maybe something went wrong with the connection, so at this point I looked on the great Internet trying to find an explanation... And I found one : 

http://uwsgi-docs.readthedocs.org/en/latest/ThingsToKnow.html#things-to-know-best-practices-and-issues-read-it

> If an HTTP request has a body (like a POST request generated by a form), you have to read (consume) it in your application. If you do not do this, the communication socket with your webserver may be clobbered. If you are lazy you can use the post-buffering option that will automatically read data for you. For Rack applications this is automatically enabled.

So, looking at [validate_client](https://github.com/CanalTP/Chaos/blob/master/chaos/validate_params.py#L39-L59) function, it leads to another function named [get_client_code(request)](https://github.com/CanalTP/Chaos/blob/master/chaos/utils.py#L311-L314) and in this function if I add the line `data = request.data`, it makes the post method working properly ! :tada: 

I don't know how you want to handle that problem but let me know what do you think about this. We can manage this with an uwsgi option but it is not recommended :(.

Thank you for your attention @datanel @tchevily @azime @vincentlepot

**Comment by eturck** [comment]
During our last meeting you told us you were going to talk about it with @kinnou02 again to see what the best solution was. Do you have any update?

**Comment by kinnou02** [comment]
Nobody talked to me ;)
If I have correctly understand, it bother you to consume data if it will be use later and it can prevent some error to be raised.

Does the data need to be consumed early in the process or it should be done anytime before returning a response?
If the timing has no importance we can use a ```after_request``` in place of the ```before request```.

Another way can be to use a middleware wsgi, since this problem seem to only exist with uwsgi you can probably even do it without modifying chaos.

Last thing, the post buffering of wsgi, I don't seem where it's not recommended, the only  [documentation](http://uwsgi-docs.readthedocs.io/en/latest/Fastrouter.html#post-buffering-mode-uwsgi-2-0-9) I found is for the FastRouter, but the consequence will likely be the same: it will break a lot of things but I don't think that we use any of these features or plan to.

**Comment by vpassama** [comment]
Ok. I admit I didn't try to know more about post-buffering option because I read quickly in a post that it could effectivly break things and it made me fear this solution. But the good news is that it works :].

Just to summarize, the problem is not to consume data if it is used later because in this case chaos does it good. The problem is to consume data if the headers are invalid or missing. In this case, the decorators `validate_id` or `validate_client` bypass everything and send an error response before data consumption. Then the connection is reseted between uwsgi and nginx and the client waits until timeout is reached.

I think we can close this issue if you don't want to handle this specific problem in chaos. Thank you @kinnou02.
