### ISSUE TITLE
Cleanup multiple functionnal doc

### ISSUE THREAD

**Issue by pbougue** [CanalTP/Chaos#203]
There are multiple sources when searching for functionnal documentation:
https://github.com/CanalTP/Chaos/blob/master/documentation/disruptions.md
https://github.com/CanalTP/Chaos/blob/master/documentation/disruptions_fr.md
http://docs.chaos.apiary.io/#
http://docs.ogv2ws.apiary.io/#

(apiary links in doc are outdated)
They are not all maintained, and it's hard to know which is right, which is wrong... So cleaning down to a unique (up-to-date) English doc might be good.

**Comment by dvdn** [comment]
Done, only https://github.com/CanalTP/Chaos/blob/master/documentation/disruptions.md remains
