### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by vpassama** [CanalTP/Chaos#226]
Hi,

I wanted to try the new CHAOS version 0.35.9 and I got some errors when I post a new disruption.
This is just some feedback in order to improve CHAOS documentation.

## First error:
```
Traceback (most recent call last):
  [...]
  File "/var/www/chaos/.venv/lib/python2.7/site-packages/redis/connection.py", line 253, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting localhost:6379. Connection refused.
```

I installed redis-server on my VM in order to make it working. I know it can be configured as 'simple' in configuration file too but I had to look at flask-cache documentation as your default settings file declares CACHE_TYPE='redis'.
I think it should be mentioned in the documentation somewhere just to avoid surprises as everything is working but disruptions POST/PUT requests.

## Second error:

I lost the traceback :) but it's about tyr. I wanted to post a disruption and the connection with tyr database failed. As tyr is not mandatory for jormungandr/kraken, I forgot to install it. I think it should be mentioned too in the documentation as there is no way of disabling it in the settings file (or maybe there is one but I didn't found it).

Thank you.

**Comment by vincentlepot** [comment]
Hi Vincent!

Regarding the first part of the issue, README.md has been updated regarding the cache, and the default_settings.py now shows all the configuration variables (you can set using environment variables if you want to use it as a docker container for instance)

**Comment by vincentlepot** [comment]
Regarding the Tyr issue, I don't see where the link is. Chaos does not use neither Tyr nor the jormungandr db... Do you have a case to reproduce?

**Comment by dvdn** [comment]
Hi Vincent, since no returns on this issue.
We close, thx.
